### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.chartiq.sdk.ChartIQ.evaluateJavascript

### ISSUE THREAD

**Issue by ANEESHGitHub** [ChartIQ/Charting-Library---Android-SDK#5]
Hi,  
 I am using  chartIQ library, and when I run it on devices like mi or Lenovo K3 Note, app getting crashed.  I have collected the crash log regarding it, see the following crash log:

Crashed: main
       at com.git.flipmea.ui.custom.chartIQ.fragments.ChartFragment$3.run(ChartFragment.java:132)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5769)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
--

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.chartiq.sdk.ChartIQ.evaluateJavascript(java.lang.String, android.webkit.ValueCallback)' on a null object reference
       at com.git.flipmea.ui.custom.chartIQ.fragments.ChartFragment$3.run(ChartFragment.java:132)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5769)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

And, the scrip I passed is : "stxx.appendMasterData({"Last": " + ltp + ", \"DT\":new Date(" + cal.getTimeInMillis() + ")}, null, null);"

**Comment by jdrichards50** [comment]
Thanks, we'll take a look into your issue and see if we can duplicate.
